### ISSUE TITLE
Installing requirements fails with Python 3.7

### ISSUE THREAD

**Issue by rlouf** [parsing-science/pymc3_models#20]
I tried to re-build the library after upgrading to Python 3.7, and the compilation of pandas and numpy fail. After some investigation it turns out the version of numpy and pandas specified int the `requirements.txt` rely on an outdated version of Cython.

https://github.com/pandas-dev/pandas/issues/21785

It's easily fixed by bumping the version of pandas and numpy. Are there any particular reasons to keep the curent versions?

**Comment by parsing-science** [comment]
I changed the requirements file so that it specifies minimum versions instead of requiring a specific version.
