### ISSUE TITLE
models: naive bayes

### ISSUE THREAD

**Issue by rlouf** [parsing-science/pymc3_models#4]
I am currently implementing Naive Bayes, and have a working version for the normal case (with predictions), but I am not sure how to graciously handle the multinomial and bernouilli cases. Scikit-learn [wraps all 3 in different functions](http://scikit-learn.org/stable/modules/naive_bayes.html) but somehow it does not feel right. I was thinking about checking the input values (float, int or binary) and choosing the more appropriate model, but I am not sure. Any idea?

**Comment by parsing-science** [comment]
I don't have much experience with Naive Bayes. If you have a particular dataset you're trying to fit, maybe just implement whichever version is relevant to you first. You can always go back and add the other versions later.
