### ISSUE TITLE
models: hierarchical logistic regression

### ISSUE THREAD

**Issue by rlouf** [parsing-science/pymc3_models#9]
I am writing documentation for the various models (a bit like scikit-learn's user guides), and I am struggling to understand `HierarchicalLogisticRegression`:

- The number of categories can be > 2, yet the probability of belonging to a category is given by a Bernouilli distribution;
- What is the `cats` variable useful for?

I would replace `Bernoulli` with `Categorical` and write directly `temp = alpha + T.sum(beta*model_input, 1)` or something like that. But maybe there is something I don't understand.

**Comment by parsing-science** [comment]
Hi, did you watch the PyData NYC talk I gave about this model? I think that should clear up some of these issues.
